export const proteinColorSchemes = {
    dssp8: {
        primary : {
            'G':'#33cc00',
            'H':'#009900',
            'I':'#33cc00',
            'B':'#666666',
            'E':'#0033ff',
            'S':'#0099ff',
            'T':'#0099ff',
            'C':'#ffff00',
        },
        contrast : {
            'G':'#fafafa',
            'H':'#fafafa',
            'I':'#fafafa',
            'B':'#fafafa',
            'E':'#fafafa',
            'S':'#fafafa',
            'T':'#fafafa',
            'C':'#505050',
        }
    },
    disorder: {
        primary : {
            '-':'#505050',
            'X':'#fafafa',
        },
        contrast : {
            '-':'#fafafa',
            'X':'#505050',
        }
    },
    mview: {
        primary : {
            '.':'#fafafa',
            '-':'#fafafa',
            'G':'#33cc00',
            'A':'#33cc00',
            'I':'#33cc00',
            'V':'#33cc00',
            'L':'#33cc00',
            'M':'#33cc00',
            'F':'#009900',
            'Y':'#009900',
            'W':'#009900',
            'H':'#009900',
            'C':'#ffff00',
            'P':'#33cc00',
            'K':'#cc0000',
            'R':'#cc0000',
            'D':'#0033ff',
            'E':'#0033ff',
            'Q':'#6600cc',
            'N':'#6600cc',
            'S':'#0099ff',
            'T':'#0099ff',
            'B':'#666666',
            'Z':'#666666',
            'X':'#666666',
            '?':'#999999',
            '*':'#666666',
            'U':'#000000'
        },
        contrast : {
            '.':'#fafafa',
            '-':'#fafafa',
            'G':'#fafafa',
            'A':'#fafafa',
            'I':'#fafafa',
            'V':'#fafafa',
            'L':'#fafafa',
            'M':'#fafafa',
            'F':'#fafafa',
            'Y':'#fafafa',
            'W':'#fafafa',
            'H':'#fafafa',
            'C':'#505050',
            'P':'#fafafa',
            'K':'#fafafa',
            'R':'#fafafa',
            'D':'#fafafa',
            'E':'#fafafa',
            'Q':'#fafafa',
            'N':'#fafafa',
            'S':'#fafafa',
            'T':'#fafafa',
            'B':'#fafafa',
            'Z':'#fafafa',
            'X':'#fafafa',
            '?':'#fafafa',
            '*':'#fafafa',
            'U':'#fafafa'
        }
    },
};